spring:
  profiles:
    active: default

  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=CompanyManagement;trustServerCertificate=true;encrypt=true
    username: sa
    password: YourStrong@Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
    validate-on-migrate: true
    locations: classpath:db/migration
